### ISSUE TITLE
Localize the `Anonymous` user name

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyter_collaboration#100]
At the moment `Anonymous` is defined here:

https://github.com/jupyterlab/jupyterlab/blob/c26b3159e6e1149b60089f2c6e4d694cad78c745/packages/docprovider/src/awareness.ts#L89

But could be localized using the `ITranslator`

**Comment by fcollonval** [comment]
Closing in favor of https://github.com/jupyter-server/jupyter_server/issues/1220
