### ISSUE TITLE
Multiple cursors not showing up in RTC

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyter_collaboration#102]
![multi-cursor](https://user-images.githubusercontent.com/5832902/118116796-a2c91500-b3e2-11eb-9e46-40dbcc47e200.gif)

### Problem

Extra CodeMirror cursors set by Ctrl + click do not show up on the collaborator view of the editor, nor does the extra selection. It would be nice to have multi-cursor mode work better with RTC.

**Comment by hbcarlos** [comment]
fixed in #122
