### ISSUE TITLE
Browser tab title not readable

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyter_collaboration#110]
## Description

When opening a document from the YDrive the browser tab title will show something like `YDrive%3AUnt… - JupyterLab`:

![image](https://user-images.githubusercontent.com/591645/221244533-b1cc78cd-1580-4a49-a414-5d0a6b018ab5.png)

This is not very readable and it also looks like there is an decoding issue.

## Reproduce

Test JupyterLab master branch with Binder, which has RTC enabled.

## Expected behavior

Ideally the browser tab title should display something more readable like JupyterLab without RTC does (screenshot taken from the latest master), which shows `Untitled.ipynb` in this example:

![image](https://user-images.githubusercontent.com/591645/221244146-8afd3634-7351-4344-a651-0b665c5cc16a.png)

**Comment by jtpio** [comment]
Actually this might also be an issue in core JupyterLab with how `title` is updated with files from custom drives.

Feel free to move the issue if so.

**Comment by hbcarlos** [comment]
> Actually this might be an issue in core JupyterLab with how the title is updated with files from custom drives.

Yes, it looks like a core issue.
Anyway, we will have to fix it ourselves, so let's leave the issue here; otherwise, it will get lost between JupyterLabs issues.

**Comment by JasonWeill** [comment]
We saw this during the 2023-03-01 JupyterLab meeting, where we used RTC for collaboration on notes.
