### ISSUE TITLE
Rename endpoints

### ISSUE THREAD

**Issue by hbcarlos** [jupyterlab/jupyter_collaboration#111]
The endpoints we use are scoped under `/api/yjs`. Maybe we should rename them to use a meaningful name. For example, we could use something like `documents`.

https://github.com/jupyterlab/jupyter_collaboration/blob/d8481ce01934a671e5da049f31062bbbb6bccd56/jupyter_collaboration/app.py#L60-L61

**Comment by jtpio** [comment]
Good catch :+1: 

> we could use something like `documents`.

Sounds good. Maybe worth checking there is no existing server extension using that endpoint? Otherwise `collaboration` might also work?

**Comment by davidbrochart** [comment]
I think we should make it clear that it's different than `/api/contents`, and `documents` seems too similar.
`collaboration` is more aligned with the name of this repository.

**Comment by hbcarlos** [comment]
I like `collaboration`. It distinguishes better the endpoint from `contents`, and at the same time, it is generic enough (we are also using this endpoint for transient rooms, rooms without a document).

In addition, this could be a solution for @krassowski comment [here](https://github.com/jupyterlab/jupyterlab/issues/14031#issuecomment-1445164761)

> My naive understanding is that both are server extensions and hence both register API endpoints. This is why I am concerned, but maybe this is not a problem? Thanks for engaging in brainstorming what may be the implications for users!
